### ISSUE TITLE
Vacosa completa mudar cor do progress bar para verde

### ISSUE THREAD

**Issue by rodrigocorreaecastro** [tmarquesini/vacosas#14]
Uma vacosa finalizada poderia fica em verde o progress bar, assim tendo um destaque entre as que se encontram em andamento.

**Comment by tmarquesini** [comment]
Vacosas foram divididas em duas páginas. a padrão mostra apenas vacosas abertas e nela há um link para exibir as que já fecharam. Alteração realizada pelo @Georde
